### ISSUE TITLE
go get -v -t ./...       unexpected directory layout

### ISSUE THREAD

**Issue by scottstensland** [SilentGopherLnx/GopherFileManager#1]
getting this error when installing imports

```
wild@owl /cryptdata6/var/log/tmp/shared/gopath/src/github.com/SilentGopherLnx/GopherFileManager $ go get -v -t ./...
unexpected directory layout:
	import path: _/cryptdata6/var/log/tmp/shared/gopath/src/github.com/SilentGopherLnx/GopherFileManager/pkg_fileicon
	root: /cryptdata6/var/log/tmp/shared/gopath/src
	dir: /cryptdata6/var/log/tmp/shared/gopath/src/github.com/SilentGopherLnx/GopherFileManager/pkg_fileicon
	expand root: /cryptdata6/var/log/tmp/shared/gopath
	expand dir: /cryptdata6/var/log/tmp/shared/gopath/src/github.com/SilentGopherLnx/GopherFileManager/pkg_fileicon
	separator: /

```

**Comment by SilentGopherLnx** [comment]
I have not tried to do it like this.
Can you try just downloading the full directory from site?

**Comment by scottstensland** [comment]
I did a git clone of this repo then I got above error when attempting to compile this project ... which is a very common standard way to install the necessary upstream libraries

how are you compiling this project ?

**Comment by SilentGopherLnx** [comment]
via "LiteIDE" and "run and compile" button
you tried this?
    sudo apt-get install libgtk-3-dev
    sudo apt-get install libcairo2-dev
    sudo apt-get install libglib2.0-dev

**Comment by scottstensland** [comment]
yes I already had all those packages installed ...  I will take a look at   LiteIDE

**Comment by SilentGopherLnx** [comment]
It seems like I should try to install and run this on a clear virtual machine when I have time for this next time =(

**Comment by SilentGopherLnx** [comment]
I found the problem on virtual machine:
I see you made "GO111MODULE=off".
It seems "go get" does not like imports like "./something".
I changed it to "github.com/SilentGopherLnx/GopherFileManager/something" in each file. After it "go build" works
Already uploaded to github
